server:
  error:
    include-stacktrace: on_param
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: adriano
    password: sara 123
  jpa:
    hibernate:
      ddl-auto: update
